document.getElementById('ingles').addEventListener('click',function(){
document.getElementById("demo").innerHTML="Traducido a ingles"
document.getElementById("tituloinformacionpersonal").innerHTML="Personal information"
document.getElementById("nombreapellido").innerHTML="Name And Surname : "
document.getElementById("edad").innerHTML="Age : 18 years"
document.getElementById("nacimiento").innerHTML="Date of Birth : 5/15/2005"
document.getElementById("direccion").innerHTML="Address: Las Heras 2056"
document.getElementById("cel").innerHTML="Personal Phone: 3458515097"
document.getElementById("educaciontitulo").innerHTML="Academic training"
document.getElementById("educacion1").innerHTML="Primary School: Adm. William Brown, No. 1250"
document.getElementById("educacion2").innerHTML="Secondary School: Domingo Guzman Silva Superior Normal School of Commerce"
document.getElementById("educacion3").innerHTML="Tertiary: Higher Institute No. 9105 Dra. Sara Faisal"
document.getElementById("educacion4").innerHTML="University: Studying ING in systems at, UTN Santa Fe - UTN Facultad Regional Santa Fe"
document.getElementById("tituloexperiencia").innerHTML="Work experience"
document.getElementById("exp1").innerHTML="Training: 1 years in Telecom Company"
document.getElementById("exp2").innerHTML="Mobile application developer: 1 year at FRAVEGA"
document.getElementById("exp3").innerHTML="WEB Developer: PLATZI Platform"
document.getElementById("sobremi").innerHTML="About me"
document.getElementById("mi1").innerHTML="Hobbies : <span>Electronics</span><span>Programming</span> "
document.getElementById("mi2").innerHTML="Languages : <span>Spanish</span> <span>English</span>"
document.getElementById("mi3").innerHTML="Sports : <span>Soccer</span> <span>Boxing</span"
document.getElementById("mi4").innerHTML="Programming languages : <span>Python</span> <span>C++</span> "
document.getElementById("titulocontacto").innerHTML="Contact"

});

document.getElementById('español').addEventListener('click',function(){
    document.getElementById("demo").innerHTML="Traducido a español"
    document.getElementById("tituloinformacionpersonal").innerHTML="Informacion Personal"
    document.getElementById("nombreapellido").innerHTML="Nombre y Apellidos : "
    document.getElementById("edad").innerHTML="Edad :                18 años"
    document.getElementById("nacimiento").innerHTML="Fecha De Nacimiento : 15/5/2005"
    document.getElementById("direccion").innerHTML="Direccion :           Las Heras 2056"
    document.getElementById("cel").innerHTML="Telefono Personal :   3458515097"
    document.getElementById("educaciontitulo").innerHTML="Formacion Academica"
    document.getElementById("educacion1").innerHTML="Escuela Primaria :        Almte. Guillermo Brown, N° 1250"
    document.getElementById("educacion2").innerHTML="Escuela Secundaria :    Escuela Normal Superior de Comercio Domingo Guzman Silva"
    document.getElementById("educacion3").innerHTML="Terciario :             Instituto Superior N° 9105 Dra. Sara Faisal"
    document.getElementById("educacion4").innerHTML="Universidad :           Cursando ING en sistemas en, UTN Santa Fe - UTN Facultad Regional Santa Fe"
    document.getElementById("tituloexperiencia").innerHTML="Experiencia Laboral"
    document.getElementById("exp1").innerHTML="Training : 1 años en Empresa Telecom"
    document.getElementById("exp2").innerHTML="Desarrollador de aplicaciones moviles : 1 año en FRAVEGA"
    document.getElementById("exp3").innerHTML="Desarrollador WEB : Plataforma PLATZI"
    document.getElementById("sobremi").innerHTML="Sobre Mi"
    document.getElementById("mi1").innerHTML="Hobbies : <span>Electronica</span><span>Programacion</span> "
    document.getElementById("mi2").innerHTML="Idiomas :  <span>Español</span> <span>Ingles</span>"
    document.getElementById("mi3").innerHTML="Deportes : <span>Futbol</span> <span>Boxeo</span"
    document.getElementById("mi4").innerHTML="Lenguajes De Programacion : <span>Python</span> <span>C++</span> "
    document.getElementById("titulocontacto").innerHTML="Contacto"
});